version: '3.1'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway # 도커 컴포즈 커맨드로 오버라이드 됨
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3000:3000' # 임시
    volumes:
      - .:/usr/src/app 
      # - /usr/src/app/node_modules
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm run start:dev user # 도커 컴포즈 커맨드로 오버라이드 됨
    depends_on:
      postgres_user:
        condition: service_healthy
    env_file:
      - ./apps/user/.env
    ports:
      - '3001:3000' # 임시
    volumes:
      - .:/usr/src/app 
      # - /usr/src/app/node_modules

  postgres_user:
    image: postgres:16
    env_file:
      - ./apps/user/.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '6001:5432'
    volumes:
      - ./postgres/user:/var/lib/postgresql/data
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      test: ["CMD-SHELL", "pg_isready -d yeowoobi-db -U yeowoo"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  book-log:
    build: 
      context: .
      dockerfile: ./apps/book-log/Dockerfile
      target: development
    command: pnpm run start:dev book-log
    depends_on:
      postgres_book-log:
        condition: service_healthy
    env_file:
      - ./apps/book-log/.env
    ports:
      - '3002:3000'
    volumes:
      - .:/usr/src/app

  postgres_book-log:
    image: postgres:16
    env_file:
      - ./apps/user/.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '6002:5432'
    volumes:
      - ./postgres/book-log:/var/lib/postgresql/data
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      test: ["CMD-SHELL", "pg_isready -d yeowoobi-booklog-db -U yeowoo"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s